[package]
name = "inngest-state"
version = "0.1.0"
edition = "2024"
description = "State management system for Inngest with Redis backend"

[dependencies]
# Core dependencies
inngest-core = { workspace = true }

# Async runtime
tokio = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }

# Redis client
fred = { workspace = true }

# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# IDs and time
uuid = { workspace = true }
ulid = { workspace = true }
chrono = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Async traits
async-trait = { workspace = true }

# Logging and tracing
tracing = { workspace = true }

# Data structures
dashmap = { workspace = true }
parking_lot = { workspace = true }
bytes = { workspace = true }

# Hashing
sha1 = { workspace = true }
sha2 = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
pretty_assertions = { workspace = true } 