[package]
name = "inngest-config"
version = "0.1.0"
edition = "2021"
description = "Configuration management for Inngest"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
anyhow = { workspace = true }
config = { workspace = true }
