[package]
name = "inngest-execution"
version = "0.1.0"
edition = "2021"
description = "Execution engine for Inngest functions"

[dependencies]
# Core dependencies
inngest-core = { path = "../inngest-core" }
inngest-state = { path = "../inngest-state" }
inngest-queue = { path = "../inngest-queue" }
inngest-events = { path = "../inngest-events" }

# Async runtime
tokio = { version = "1.35", features = ["full"] }
async-trait = "0.1.77"
futures = "0.3.30"

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Utilities
uuid = { version = "1.6", features = ["v4", "serde"] }
ulid = { version = "1.1", features = ["serde"] }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "1.0"
anyhow = "1.0"

# Observability
tracing = "0.1"
tracing-futures = "0.2"

# HTTP client
reqwest = { version = "0.11", features = ["json", "stream"] }
url = "2.5"

# Rate limiting and concurrency
governor = "0.6"
dashmap = "5.5"

# Batch processing
redis = { version = "0.24", features = ["tokio-comp"] }
seahash = "4.1"

[dev-dependencies]
tokio-test = "0.4"
mockall = "0.12"
pretty_assertions = "1.4" 