[package]
name = "inngest-core"
version = "0.1.0"
edition = "2024"
description = "Core data structures and traits for Inngest"

[dependencies]
# Serialization
serde = { workspace = true }
serde_json = { workspace = true }

# IDs and time
uuid = { workspace = true }
ulid = { workspace = true }
chrono = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Async traits
async-trait = { workspace = true }

# Hashing
sha1 = { workspace = true }
sha2 = { workspace = true }
xxhash-rust = { workspace = true }

# Protobuf
prost = { workspace = true }
prost-types = { workspace = true }

# Base64 for event handling
base64 = { workspace = true }

[dev-dependencies]
tokio-test = { workspace = true }
pretty_assertions = { workspace = true }